In [1]:
import data
import data_vectorizer
import pandas as pd
import numpy as np
import model_vectorizer_simple
import data_vectorizer_tf

D:\KaggleLearningEquality2023\data_vectorizer_tf.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contents_vect["title_vectorize"] = contents_vect["title_vectorize"].apply(transform_string_to_list)
D:\KaggleLearningEquality2023\data_vectorizer_tf.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contents_vect["description_vectorize"] = contents_vect["description_vectorize"].apply(transform_string_to_list)
D:\KaggleLearningEquality2023\data_vectorizer_tf.py:27: SettingWithCopyWarning: 
A value is tryi

In [8]:
x = np.array([np.array([2]), np.array([3,4])], dtype = "object")
x[0].dtype

dtype('int32')

In [5]:
display(data_vectorizer.train_contents.where(data_vectorizer.train_contents.isin(["c_433f60c8c551"])))

Index([            None, 'c_433f60c8c551',             None,             None,
                   None,             None,             None,             None,
                   None,             None,
       ...
                   None,             None,             None,             None,
                   None,             None,             None,             None,
                   None,             None],
      dtype='object', name='id', length=80172)

In [9]:
np.where(data_vectorizer.train_contents.isin(["c_433f60c8c551"]))[0]

array([1], dtype=int64)

In [13]:
initial_sample_size = 10000
contents_list = np.random.choice(len(data_vectorizer.train_contents), initial_sample_size, replace=False)
topics_list = np.random.choice(len(data_vectorizer.train_topics), initial_sample_size + 1, replace=False)

import time
ctime = time.time()
res = data_vectorizer.obtain_correlation_frame(data_vectorizer.train_topics[topics_list], data_vectorizer.train_contents[contents_list])
ctime = time.time() - ctime
print("time: ",ctime)

ctime = time.time()
res2 = data_vectorizer_tf.obtain_correlations_matrix_train(topics_list, contents_list)
ctime = time.time() - ctime
print("time: ",ctime)

display(res)
display(res2)
display((res.to_numpy().astype(np.int32) != res2.astype(np.int32)).sum())

time:  0.8634531497955322
time:  0.09372782707214355


c_2254507905b1  c_a4c6bc182617  c_675ba6d2db42  \
t_7e88abbe1389             0.0             0.0             0.0   
t_46c2223c25e0             0.0             0.0             0.0   
t_e9772871b82c             0.0             0.0             0.0   
t_7d8acb4ebf4f             0.0             0.0             0.0   
t_0fcafeb23f70             0.0             0.0             0.0   
...                        ...             ...             ...   
t_54ce39a63f89             0.0             0.0             0.0   
t_0c0c7a677c50             0.0             0.0             0.0   
t_a7431212ed19             0.0             0.0             0.0   
t_6d60c0c2e834             0.0             0.0             0.0   
t_4d3c71b75f0a             0.0             0.0             0.0   

                c_f2a11c5d2256  c_cde3a79397ee  c_470a4a9a79ed  \
t_7e88abbe1389             0.0             0.0             0.0   
t_46c2223c25e0             0.0             0.0             0.0   
t_e9772871b82c             0.0             0.0             0.0   
t_7d8acb4ebf4f             0.0             0.0             0.0   
t_0fcafeb23f70             0.0             0.0             0.0   
...                        ...             ...             ...   
t_54ce39a63f89             0.0             0.0             0.0   
t_0c0c7a677c50             0.0             0.0             0.0   
t_a7431212ed19             0.0             0.0             0.0   
t_6d60c0c2e834             0.0             0.0             0.0   
t_4d3c71b75f0a             0.0             0.0             0.0   

                c_80899063fcb9  c_14757b5d634b  c_08e41dd6ae40  \
t_7e88abbe1389             0.0             0.0             0.0   
t_46c2223c25e0             0.0             0.0             0.0   
t_e9772871b82c             0.0             0.0             0.0   
t_7d8acb4ebf4f             0.0             0.0             0.0   
t_0fcafeb23f70             0.0             0.0             0.0   
...                        ...             ...             ...   
t_54ce39a63f89             0.0             0.0             0.0   
t_0c0c7a677c50             0.0             0.0             0.0   
t_a7431212ed19             0.0             0.0             0.0   
t_6d60c0c2e834             0.0             0.0             0.0   
t_4d3c71b75f0a             0.0             0.0             0.0   

                c_5257fb8c8cdc  ...  c_c8401ce8197a  c_06e435c5adc4  \
t_7e88abbe1389             0.0  ...             0.0             0.0   
t_46c2223c25e0             0.0  ...             0.0             0.0   
t_e9772871b82c             0.0  ...             0.0             0.0   
t_7d8acb4ebf4f             0.0  ...             0.0             0.0   
t_0fcafeb23f70             0.0  ...             0.0             0.0   
...                        ...  ...             ...             ...   
t_54ce39a63f89             0.0  ...             0.0             0.0   
t_0c0c7a677c50             0.0  ...             0.0             0.0   
t_a7431212ed19             0.0  ...             0.0             0.0   
t_6d60c0c2e834             0.0  ...             0.0             0.0   
t_4d3c71b75f0a             0.0  ...             0.0             0.0   

                c_645ddadb9929  c_27ded2a9d76e  c_07e347b54b8e  \
t_7e88abbe1389             0.0             0.0             0.0   
t_46c2223c25e0             0.0             0.0             0.0   
t_e9772871b82c             0.0             0.0             0.0   
t_7d8acb4ebf4f             0.0             0.0             0.0   
t_0fcafeb23f70             0.0             0.0             0.0   
...                        ...             ...             ...   
t_54ce39a63f89             0.0             0.0             0.0   
t_0c0c7a677c50             0.0             0.0             0.0   
t_a7431212ed19             0.0             0.0             0.0   
t_6d60c0c2e834             0.0             0.0             0.0   
t_4d3c71b75f0a             0.0             0.0            

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

0

In [4]:
print(len(data_vectorizer_tf.train_correlations))
print(len(data_vectorizer.train_topics))

46149
46149


In [12]:
np.where(np.array([2,3,5,2,1,7]) == 2)[0]

array([0, 3], dtype=int64)

In [12]:
display(data_vectorizer.train_contents)
lookup = pd.Series(index = data_vectorizer.train_contents, data = range(len(data_vectorizer.train_contents)))
tuple(lookup.loc[['c_bd6cb0b2064a', 'c_433f60c8c551', 'c_af05b751efdf']])

Index(['c_e1d73acfff8e', 'c_433f60c8c551', 'c_bd6cb0b2064a', 'c_af05b751efdf',
       'c_d95c204965eb', 'c_82fff6f5f011', 'c_e7422d30f9de', 'c_5aee85b81df4',
       'c_ee5fdde42578', 'c_6287bfd9a353',
       ...
       'c_bc0c2f38405e', 'c_d1f6e1a4fdeb', 'c_d6152aa64456', 'c_d9f883585fae',
       'c_f281dc119ead', 'c_06e435c5adc4', 'c_1d988f48dbd1', 'c_9535009492ec',
       'c_d4456fa82c93', 'c_a3764558c917'],
      dtype='object', name='id', length=80172)

(2, 1, 3)

In [17]:
topic = "t_00102869fbcb"
for content in data.correlations.loc[topic, "content_ids"].split():
    if content not in data_vectorizer.train_contents:
        print(content)

c_10dbed87d839
c_964f18665f78
c_97f7c60035ea


In [18]:
pd.Index(["test", "ooo", "lol"])

Index(['test', 'ooo', 'lol'], dtype='object')

In [30]:
print(data_vectorizer.train_topics)
display(data.correlations.loc[data_vectorizer.train_topics.intersection(data.correlations.index)])

Index(['t_000095e03056', 't_00069b63a70a', 't_0008a1bd84ba', 't_000c0c854f0b',
       't_000d1fb3f2f5', 't_00102869fbcb', 't_001139e52dbe', 't_0012a45fa09c',
       't_0015856edda8', 't_00165488ad43',
       ...
       't_ffee896af9ab', 't_fff1f01cfeb0', 't_fff51448598c', 't_fff5da49c4d3',
       't_fff7782561f4', 't_fff80f4eee89', 't_fff830472691', 't_fffb0bf2801d',
       't_fffe14f1be1e', 't_fffe88835149'],
      dtype='object', name='id', length=46149)


content_ids
t_00069b63a70a                                     c_11a1dc0bfb99
t_0008a1bd84ba                      c_7ff92a954a3d c_8790b074383e
t_000d1fb3f2f5  c_07f1d0eec4b2 c_15a6fb858696 c_175e9db3fc44 c...
t_00102869fbcb  c_005e793bd0c5 c_066737fa5146 c_08b2070f92e0 c...
t_0012a45fa09c                                     c_dde078b8ea7a
...                                                           ...
t_fff51448598c  c_054e15d2ff3f c_113437812aa0 c_9c817a2bcb3c c...
t_fff5da49c4d3                      c_4a0305f5876d c_cbceabf1d5d6
t_fff7782561f4                                     c_bca8280a9ad1
t_fff830472691                      c_61fb63326e5d c_8f224e321c87
t_fffe14f1be1e                                     c_cece166bad6a

[36645 rows x 1 columns]

In [38]:
np.where(data_vectorizer.train_contents == "c_15a6fb858696")[0]

array([14213], dtype=int64)

In [17]:
print(data_vectorizer_tf.train_correlations)

((), (36008,), (26049, 26050), (), (13944, 14213, 14184, 14214, 10057, 14215, 10058, 14216, 14185, 17822, 13945, 14217, 13946, 10059, 10060, 13947, 14218, 10061, 10062, 14219, 14186, 10063, 10064, 14220, 14187, 13948), (5274, 75035, 10614, 75036, 20829, 1032, 1362, 89, 2449, 10039, 75037, 4867, 10114, 9759, 1398, 75038, 75039, 9538, 1363, 222, 6914, 75040, 6921, 75041, 1399, 2581, 75042, 9761, 16108, 4750, 9762, 2582, 1338, 2450, 1339, 3837, 2386, 10117, 3305, 7621, 6840, 1579, 10118, 7622, 10618, 5275, 2387, 75043, 10048, 75044, 4751, 75045, 10120, 9763, 4868, 10122, 3306, 75046, 75047, 5276, 10127, 218, 10129, 10130, 1400, 2780, 6915, 2583, 1580, 1033, 7623, 1340, 75048, 1401, 75049, 4869, 10052, 75050, 2293, 75051, 2451, 219, 75052, 4752), (), (17221,), (), (), (43638, 43639, 43640, 43641, 43642), (0,), (), (1,), (37772,), (9357, 9358), (37773,), (13236, 13886, 13887, 13888), (4118,), (37774,), (), (25299,), (9359, 9360, 9361, 9362), (42729, 42730), (3,), (9759, 9760, 19404, 9762, 1

In [18]:
print(data_vectorizer_tf.train_correlations[[2,5,6]])

TypeError: tuple indices must be integers or slices, not list

In [19]:
x = np.array(["test", {"lol":4, "e":3}])

In [22]:
x[1]

{'lol': 4, 'e': 3}

In [12]:
x = np.random.randint(10, size = 10)
print(x)
x[[3,5,-2]]

[8 7 1 4 8 2 8 2 3 1]


array([4, 2, 3])

In [9]:
initial_sample_size = 30
contents_list = np.random.choice(4000, initial_sample_size, replace=False)
topics_list = np.random.choice(3000, initial_sample_size, replace=False)

print(contents_list)
print(topics_list)

prod = itertools.product(list(topics_list), list(contents_list))
lists = list(zip(*prod))
arr1, arr2 = np.array(list(lists[1])), np.array(list(lists[0]))

arr3, arr4 = np.tile(contents_list, len(topics_list)), np.repeat(topics_list, len(contents_list))

print((arr1 != arr3).sum())
print((arr2 != arr4).sum())

[  91 1142 1836 3280 1768  301 1059  531 1734 1826  590 3308  419 1407
 1616 2496 3379 3495 2908  846 1331 3066 2808 1914 1113 2400 3249 1038
 3692 3206]
[2568 1228 1714 2598 2314 2405  504  795 2647  162 2185 1336 2781   17
 1866 1538  615 2455 2299 1260 1263  924 2765  581  802 2948 2042  503
 1320 1591]
0
0
