In [1]:
import numpy as np
import cupy as cp
import pandas as pd
import data

In [2]:
import time
ctime = time.time()
import data_bert
ctime = time.time() - ctime
print(ctime)

55.570743560791016


In [3]:
len(data_bert.has_correlation_contents)

279919

In [4]:
x = [2, 1, 3]
x.sort()
print(x)
x = np.array(x)
x[x<3]

[1, 2, 3]


array([1, 2])

# Check correlations

In [5]:
"""
for topic_id, mstr in data.correlations.iterrows():
    for content_id in mstr["content_ids"].split():
        content_id_int = data_bert.contents_inv_map[content_id]
        topic_id_int = data_bert.topics_inv_map[topic_id]
        if not data_bert.has_correlation(content_id_int, topic_id_int):
            print("Violation: ", topic_id, " ", content_id)
        
        if content_id_int in data_bert.train_contents_num_id and topic_id_int in data_bert.train_topics_num_id and not data_bert.has_correlations_train(np.array([content_id_int]), np.array([topic_id_int]))[0]:
            print("Violation train: ", topic_id, " ", content_id)
        if content_id_int in data_bert.test_contents_num_id and topic_id_int in data_bert.test_topics_num_id and not data_bert.has_correlations_test(np.array([content_id_int]), np.array([topic_id_int]))[0]:
            print("Violation test: ", topic_id, " ", content_id)
            
print("Finished validating correlations to has_cor")
for k in range(len(data_bert.has_correlation_topics)):
    topic_id_int = data_bert.has_correlation_topics[k]
    content_id_int = data_bert.has_correlation_contents[k]
    
    if (not data.topics.iloc[topic_id_int]["has_content"]) or (data.contents.index[content_id_int] not in data.correlations.loc[data.topics.iloc[topic_id_int].name, "content_ids"]):
        print("Violation: ", k)
print("Valid test:")
for k in range(len(data_bert.has_correlation_test_topics)):
    topic_id_int = data_bert.has_correlation_test_topics[k]
    content_id_int = data_bert.has_correlation_test_contents[k]
    
    if (not data.topics.iloc[topic_id_int]["has_content"]) or (data.contents.index[content_id_int] not in data.correlations.loc[data.topics.iloc[topic_id_int].name, "content_ids"]):
        print("Violation: ", k)
    elif topic_id_int not in data_bert.test_topics_num_id or content_id_int not in data_bert.test_contents_num_id:
        print("Violation: ", k)
print("Valid train:")
for k in range(len(data_bert.has_correlation_train_topics)):
    topic_id_int = data_bert.has_correlation_train_topics[k]
    content_id_int = data_bert.has_correlation_train_contents[k]
    
    if (not data.topics.iloc[topic_id_int]["has_content"]) or (data.contents.index[content_id_int] not in data.correlations.loc[data.topics.iloc[topic_id_int].name, "content_ids"]):
        print("Violation: ", k)
    elif topic_id_int not in data_bert.train_topics_num_id or content_id_int not in data_bert.train_contents_num_id:
        print("Violation: ", k)
print("Finished validating inverse")"""

'\nfor topic_id, mstr in data.correlations.iterrows():\n    for content_id in mstr["content_ids"].split():\n        content_id_int = data_bert.contents_inv_map[content_id]\n        topic_id_int = data_bert.topics_inv_map[topic_id]\n        if not data_bert.has_correlation(content_id_int, topic_id_int):\n            print("Violation: ", topic_id, " ", content_id)\n        \n        if content_id_int in data_bert.train_contents_num_id and topic_id_int in data_bert.train_topics_num_id and not data_bert.has_correlations_train(np.array([content_id_int]), np.array([topic_id_int]))[0]:\n            print("Violation train: ", topic_id, " ", content_id)\n        if content_id_int in data_bert.test_contents_num_id and topic_id_int in data_bert.test_topics_num_id and not data_bert.has_correlations_test(np.array([content_id_int]), np.array([topic_id_int]))[0]:\n            print("Violation test: ", topic_id, " ", content_id)\n            \nprint("Finished validating correlations to has_cor")\nfor 

In [6]:
import time
for k in range(1000):
    ctime = time.time()
    topics, contents, cors = data_bert.obtain_test_square_sample(200)
    ctime = time.time() - ctime
    if cors.sum() > 1:
        print(ctime)

        print(cors.sum())
        if (data_bert.has_correlations(contents,  topics).astype(np.int32) != cors.astype(np.int32)).astype(np.int32).sum() > 0:
            print("Violation in cors result!")

        for k in range(len(topics)):
            if topics[k] not in data_bert.test_topics_num_id:
                print("Topics violation:", topics[k], " ", k)
            if contents[k] not in data_bert.test_contents_num_id:
                print("Contents violation:", contents[k], " ", k)

0.16066408157348633
2.0
0.15627145767211914
3.0
0.15780019760131836
3.0
0.15061497688293457
3.0
0.14060425758361816
8.0
0.14059233665466309
5.0
0.15953564643859863
5.0
0.14059138298034668
7.0
0.1433725357055664
4.0
0.15055394172668457
6.0
0.14588284492492676
7.0
0.1472463607788086
5.0
0.1679537296295166
7.0
0.14417576789855957
2.0
0.1599292755126953
5.0
0.14069056510925293
5.0
0.16080403327941895
3.0
0.15155029296875
4.0
0.15280842781066895
7.0
0.1581895351409912
5.0
0.15624690055847168
2.0
0.1630260944366455
3.0
0.16360163688659668
3.0
0.16420578956604004
5.0
0.15261411666870117
4.0
0.15624189376831055
6.0
0.14062070846557617
2.0
0.14587092399597168
9.0
0.16637921333312988
5.0
0.15639162063598633
3.0
0.16359519958496094
4.0
0.1331038475036621
5.0
0.14059162139892578
9.0
0.16563773155212402
4.0
0.14914536476135254
5.0
0.14059185981750488
3.0
0.14759016036987305
4.0
0.1677703857421875
7.0
0.14062213897705078
3.0
0.15042734146118164
3.0
0.15959930419921875
6.0
0.1521470546722412
4.0
0.15

0.14435815811157227
5.0
0.1405932903289795
3.0
0.1509091854095459
5.0
0.14586591720581055
3.0
0.16144895553588867
3.0
0.15343737602233887
4.0
0.1545851230621338
3.0
0.14490652084350586
8.0
0.14059662818908691
2.0
0.14058947563171387
6.0
0.15254926681518555
4.0
0.1643359661102295
2.0
0.1505601406097412
6.0
0.16847681999206543
5.0
0.15722393989562988
4.0
0.1533827781677246
3.0
0.14255118370056152
3.0
0.14976239204406738
3.0
0.14838337898254395
6.0
0.1570749282836914
4.0
0.15991520881652832
10.0
0.1628861427307129
2.0
0.15978574752807617
5.0
0.15628600120544434
6.0
0.15201592445373535
5.0
0.15621161460876465
3.0
0.14133644104003906
4.0
0.1492919921875
4.0
0.16433215141296387
7.0
0.15578746795654297
4.0
0.1596982479095459
6.0
0.1527106761932373
2.0
0.1415870189666748
7.0
0.1533660888671875
7.0
0.14438772201538086
5.0
0.15852952003479004
5.0
0.15278983116149902
6.0
0.15987896919250488
3.0


KeyboardInterrupt: 

In [ ]:
2 in data_bert.train_topics_num_id

In [ ]:
display(data.topics.iloc[2])

In [ ]:
data.contents.index[1]

In [ ]:
np.array([])

In [18]:
ctime = time.time()
topics, contents, cors = data_bert.obtain_train_sample(50000, 50000)
ctime = time.time() - ctime

print(ctime)

print(cors.sum())
if (data_bert.has_correlations(contents,  topics).astype(np.int32) != cors.astype(np.int32)).astype(np.int32).sum() > 0:
    print("Violation in cors result!")

for k in range(len(topics)):
    if topics[k] not in data_bert.train_topics_num_id:
        print("Topics violation:", topics[k], " ", k)
    if contents[k] not in data_bert.train_contents_num_id:
        print("Contents violation:", contents[k], " ", k)

0.045862436294555664
10001.0


In [2]:
import tensorflow as tf
import numpy as np

tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
total = tf.constant(np.random.normal(size = (3,10)))
display(total)

tf.Tensor(
[[-1.69623073  1.35747747 -0.27920193  0.77807945 -1.59112723 -0.96047348
   1.58466155 -1.43993092  1.09591157  0.91974947]
 [ 0.66261955  0.51525748 -1.12547433  0.34259261  0.04000259  0.25929947
  -0.51632178 -1.75206314 -2.04440246 -1.54684577]
 [-0.87378937 -1.09496221  1.51771293 -0.5839737  -0.56794023 -0.51522008
  -2.02911168 -0.5993559   0.32229256  0.41645886]], shape=(3, 10), dtype=float64)


In [9]:
res  = tf.gather(total, np.expand_dims(np.array([2,1,0,1]), axis = 1))

In [12]:
type(res.shape[0])

int

In [4]:
import data
import numpy as np
import pandas as pd

display(data.topics["level"].value_counts())
data.topics.loc[data.topics["channel"].isin(data.channel_components[0])]["level"].value_counts()

4     38810
3     14898
5      9744
6      6210
2      4874
1      1104
7      1028
0       171
8       119
9        12
10        2
Name: level, dtype: int64

4     21469
3      8731
5      8684
6      6138
2      3098
7      1024
1       568
8       119
0       101
9        12
10        2
Name: level, dtype: int64

In [5]:
inv_map = pd.Series(index = data.topics.index, data = np.arange(len(data.topics)))

In [16]:
inv_map.loc[data.topics[data.topics["level"] == 2].index]

id
t_000095e03056        1
t_001394e54503       14
t_001477394250       15
t_002f563fc457       48
t_00349858758d       55
                  ...  
t_ffdc01d2fc47    76936
t_ffdfd53288a4    76940
t_ffe082f10e4c    76941
t_fff9e5407d13    76966
t_fffe811a6da9    76970
Length: 4874, dtype: int32

In [15]:
x = np.array(inv_map.loc[data.topics[data.topics["level"] == 2].index])
print(x)
print(x[1:])
print((x[1:] <= x[:-1]).sum())

[    1    14    15 ... 76941 76966 76970]
[   14    15    48 ... 76941 76966 76970]
0


In [4]:
data.contents.loc[data.contents["description"].apply(lambda x: type(x) == str and ("http://" in x or "https://" in x))]

title  \
id                                                                  
c_00025aaa1533                             अंग्रेजी ओके प्लीज 1.2   
c_001fd9fa012c                            Bruegel, Tower of Babel   
c_003be9e91ec7  Diabetic nephropathy - Clinical presentation &...   
c_0040d6410001                      6 हाडांना जोडून ठेवणारे सांधे   
c_0044989124e0                                     જોકરનું સંતુલન   
...                                                           ...   
c_ffccf547948b                                          1 अनुकूलन   
c_ffcf24195ae3                                रक्तदाब म्हणजे काय?   
c_ffe053c97c96                                  Role Play (Drama)   
c_ffeac1ff019d                            थ्री पिन सॉकेट टेस्टिंग   
c_ffeff039e6f7                         Шизоафективно разстройство   

                                                      description      kind  \
id                                                                            
c_00025aaa1533  source_url=http://www.prathamopenschool.org/Co...     video   
c_001fd9fa012c  Pieter Bruegel the Elder, _The Tower of Babel_...     video   
c_003be9e91ec7  Visit us (http://www.khanacademy.org/science/h...     video   
c_0040d6410001  source_url=http://www.prathamopenschool.org/Co...     video   
c_0044989124e0  source_url=http://www.prathamopenschool.org/Co...     video   
...                                                           ...       ...   
c_ffccf547948b  source_url=http://www.prathamopenschool.org/Co...     video   
c_ffcf24195ae3  source_url=http://www.prathamopenschool.org/Co...  document   
c_ffe053c97c96  source_url=http://www.prathamopenschool.org/Co...     video   
c_ffeac1ff019d  source_url=http://www.prathamopenschool.org/Co...     video   
c_ffeff039e6f7  Посети (http://www.khanacademy.org/science/hea...     video   

                                                             text language  \
id                                                                           
c_00025aaa1533                                                NaN       mr   
c_001fd9fa012c  BETH HARRIS: We're in the Kunsthistorisches Mu...       en   
c_003be9e91ec7  - [Voiceover] Diabetic nephropathy is one of t...       en   
c_0040d6410001                                                NaN       mr   
c_0044989124e0                                                NaN       gu   
...                                                           ...      ...   
c_ffccf547948b                                                NaN       hi   
c_ffcf24195ae3                                                NaN       mr   
c_ffe053c97c96                                                NaN       ur   
c_ffeac1ff019d                                                NaN       hi   
c_ffeff039e6f7  Шизоафективните разстройства са тези, при коит...       bg   

               copyright_holder      license  \
id                                             
c_00025aaa1533              NaN          NaN   
c_001fd9fa012c     Khan Academy  CC BY-NC-SA   
c_003be9e91ec7     Khan Academy  CC BY-NC-SA   
c_0040d6410001              NaN          NaN   
c_0044989124e0              NaN          NaN   
...                         ...          ...   
c_ffccf547948b              NaN          NaN   
c_ffcf24195ae3              NaN          NaN   
c_ffe053c97c96              NaN          NaN   
c_ffeac1ff019d              NaN          NaN   
c_ffeff039e6f7     Khan Academy  CC BY-NC-SA   

                                            description_translate  \
id                                                                  
c_00025aaa1533                /Sort diagrams/Default/as _inserted   
c_001fd9fa012c  Pieter Bruegel the Elder, _The Tower of Babel_...   
c_003be9e91ec7  Visit us (http://www.khanacademy.org/science/h...   
c_0040d6410001                      /Sort diagrams/Default/as ht:   
c_0044989124e0  source_url=http://www.prathamopensschool.org/C...   
...        

In [1]:
import data

In [2]:
print(data.topic_trees_contents)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [3]:
len(data.topic_trees_contents)

171

In [5]:
data.topic_trees_contents.keys()

dict_keys(['000cf7', '8e286a', '6e3ba4', '5223e0', 'ebc86c', 'e77b55', 'a91e32', '2ee29d', 'f83dcf', '9fd860', '217993', '484bd2', 'fef095', '6e90a7', 'bfc678', '0ec697', 'c7ca13', '4662df', 'ef93f0', '0c929f', '36a98b', '1fb613', 'c36745', 'ffbd13', '5139e9', 'c6dab5', 'd2ac0e', '0d3492', '05be9f', 'f9b74f', '998df9', '88c9d6', 'c88ff6', '65c955', '274269', '2765c6', 'd5fb04', '14d190', 'e7a498', '344113', '735876', 'c152d6', 'e6bdbc', 'b4897d', '9d5527', '7f116c', '7b47c5', 'bb3a0c', 'bff3ab', '410920', '60b280', 'a13d2e', 'c1d57e', '0ea5f3', '0f546a', '06fb18', '28ffa8', '4d2d4a', 'ef2088', '01dbc1', '73843d', '11171c', 'fc9105', '14cb7f', 'b14cf2', '760ea6', '7db7f2', '02be07', '6b09a4', '39979b', 'abd7dc', '1cc2ee', '7385f9', '255459', '54971d', '71fd51', 'bae253', '27d43f', '5aa8ba', '653433', '49ea7a', '686d66', 'd4eeb3', 'cf94d5', '0a9df7', '1b97a4', '03de11', '998b74', '5d4a02', 'd5963f', '239d8f', '42e8ef', 'bfdae0', '383b8a', '50fe84', 'd30518', '8bbad6', 'bbce73', '494cf2',

In [8]:
data.channel_components

[['fef095',
  '14d190',
  '0ec697',
  '2ee29d',
  '274269',
  'ef2088',
  'ebc86c',
  '760ea6',
  '217993',
  'ef93f0',
  '344113',
  'c7ca13',
  '7f116c',
  '8bbad6',
  'e77b55',
  '39979b',
  'b4897d',
  'd4eeb3',
  '383b8a',
  '50fe84',
  '5139e9',
  '6e3ba4',
  '54971d',
  '6e90a7',
  '36a98b',
  '998df9',
  '410920',
  '42e8ef',
  'fc9105',
  '8b5488',
  '484bd2',
  'd5963f',
  '7385f9',
  '71fd51',
  '64cbe8',
  'f41d17',
  '6465e0',
  '51bdd1',
  'edb272',
  'f9db19',
  '27d43f',
  '239d8f',
  '1cc2ee',
  '06fb18',
  '11171c',
  '653433',
  '14cb7f',
  '73843d',
  '05be9f',
  'd5fb04',
  '6b09a4',
  '0f546a',
  '8afc0b',
  '686d66',
  '23f9e1',
  'd30518',
  'b3f329',
  '4d2d4a',
  '03de11',
  'e7a498',
  '018d08',
  '49ea7a',
  '0a9df7',
  '4b0f81',
  '50083f',
  '9d5527',
  '735876',
  '7db7f2',
  '494cf2',
  'bda367',
  '5d4a02',
  'cfc6dd',
  '75fbe2',
  'a2924d',
  '983e56',
  'bb3a0c',
  'a91e32',
  '1dfd91',
  '4a1401',
  'ed5f98',
  'f2e966',
  '16c07b',
  'ca3996',
  '8

In [9]:
import json

with open('data/temp_topic_trees_contents.json', 'w') as f:
    json.dump(data.topic_trees_contents,f)

with open('data/temp_channel_components.json', 'w') as f:
    json.dump(data.channel_components,f)