In [1]:
import data
import data_vectorizer
import pandas as pd
import numpy as np
import model_vectorizer_simple

In [108]:
import itertools
prod = list(itertools.product([1,2,3],[4,5,6]))
print(prod)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]


In [109]:
list(zip(*prod))

[(1, 1, 1, 2, 2, 2, 3, 3, 3), (4, 5, 6, 4, 5, 6, 4, 5, 6)]

In [9]:
z = list(zip(*[(1, 2), (3, 4), (5, 6)]))

In [8]:
display(data_vectorizer.train_contents)
display(data_vectorizer.train_topics)
display(data_vectorizer.test_contents)
display(data_vectorizer.test_topics)

Index(['c_e1d73acfff8e', 'c_433f60c8c551', 'c_bd6cb0b2064a', 'c_af05b751efdf',
       'c_d95c204965eb', 'c_82fff6f5f011', 'c_e7422d30f9de', 'c_5aee85b81df4',
       'c_ee5fdde42578', 'c_6287bfd9a353',
       ...
       'c_bc0c2f38405e', 'c_d1f6e1a4fdeb', 'c_d6152aa64456', 'c_d9f883585fae',
       'c_f281dc119ead', 'c_06e435c5adc4', 'c_1d988f48dbd1', 'c_9535009492ec',
       'c_d4456fa82c93', 'c_a3764558c917'],
      dtype='object', name='id', length=80172)

Index(['t_000095e03056', 't_00069b63a70a', 't_0008a1bd84ba', 't_000c0c854f0b',
       't_000d1fb3f2f5', 't_00102869fbcb', 't_001139e52dbe', 't_0012a45fa09c',
       't_0015856edda8', 't_00165488ad43',
       ...
       't_ffee896af9ab', 't_fff1f01cfeb0', 't_fff51448598c', 't_fff5da49c4d3',
       't_fff7782561f4', 't_fff80f4eee89', 't_fff830472691', 't_fffb0bf2801d',
       't_fffe14f1be1e', 't_fffe88835149'],
      dtype='object', name='id', length=46149)

Index(['c_639ea2ef9c95', 'c_89ce9367be10', 'c_ac1672cdcd2c', 'c_ebb7fdf10a7e',
       'c_2bbc650030f4', 'c_304ee4f59410', 'c_0baf72ed7e1e', 'c_5eca28e2cdb4',
       'c_6a5472fb1483', 'c_ccd6b2522613',
       ...
       'c_c8afdc5d35e0', 'c_0a14c601790d', 'c_4296e1773043', 'c_467c25f8af6e',
       'c_50a388dd2295', 'c_5f678fecd934', 'c_686fc8da9d9e', 'c_bfaf73de8100',
       'c_dbc8b01bad08', 'c_ec8c8f6480d0'],
      dtype='object', name='id', length=41272)

Index(['t_00068291e9a4', 't_0010852b7049', 't_001477394250', 't_0014be0167f3',
       't_0014d6945f7e', 't_001bc7125ae7', 't_001bd01717d7', 't_002336d97c88',
       't_00253e2bc084', 't_002dfcaaf1d7',
       ...
       't_ffd908252a7d', 't_ffdc013937fc', 't_ffdfd53288a4', 't_ffe5264dc46d',
       't_ffe546d714a1', 't_ffe719589252', 't_fff05585df72', 't_fff5d93d4dc2',
       't_fff7f2dd208b', 't_fffe811a6da9'],
      dtype='object', name='id', length=14469)

In [104]:
initial_sample_size = 1000
contents_list = data_vectorizer.random_train_contents_sample(initial_sample_size)
topics_list = data_vectorizer.random_train_topics_sample(initial_sample_size)
cor_frame = data_vectorizer.obtain_correlation_frame(topics_list, contents_list)

print(cor_frame.sum().sum())

45.0


In [105]:
cor_mat = cor_frame.to_numpy().astype(dtype = np.int32)

zero_to_one_ratio = 100
one_locations = np.where(cor_mat == 1)
zero_locations = np.where(cor_mat == 0)
stopics = list(one_locations[0])
scontents = list(one_locations[1])

one_length = len(stopics)
zero_length = int(one_length * zero_to_one_ratio)
correlations = [1] * one_length
correlations.extend([0] * zero_length)

zero_samples = list(np.random.choice(len(zero_locations[0]), zero_length, replace=False))
stopics.extend(zero_locations[0][zero_samples])
scontents.extend(zero_locations[1][zero_samples])

stopics = topics_list[stopics]
scontents = contents_list[scontents]

for k in range(len(correlations)):
    if int(cor_frame.loc[stopics[k], scontents[k]]) != correlations[k]:
        print("Error:   ", stopics[k]," ", scontents[k])
        
print(cor_mat.sum())
print(len(correlations))

45
4545


In [58]:
rint = np.random.randint(2, size = 10)
display(rint)
display(rint[[3,1,5]])

array([0, 1, 1, 0, 1, 0, 1, 1, 0, 1])

array([0, 1, 0])

In [47]:
print(correlations)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [24]:
mat = np.random.normal(size = (11, 10))
display(mat)
display(mat.flatten())

array([[ 5.54998990e-01, -6.82801331e-01,  4.27462113e-01,
         1.56883148e+00, -3.84519873e-02, -2.91942157e-01,
        -1.84802245e+00, -4.63534869e-01, -6.46146170e-01,
        -1.06448844e+00],
       [ 1.07209767e+00, -8.04710991e-01,  6.11925974e-01,
        -5.14159239e-01,  4.85407301e-01,  7.41236000e-01,
         6.69513159e-01,  1.02792098e+00,  1.57914363e+00,
        -9.59296535e-02],
       [-4.41025254e-01,  1.45252316e+00,  9.98628448e-01,
        -4.23597907e-01,  4.44918004e-01,  1.32930609e+00,
         1.25161169e-02,  4.88572476e-01, -2.14411726e+00,
         5.79508226e-01],
       [ 9.76426066e-02,  2.36971827e-01,  1.48897919e-01,
         2.09450969e-01, -1.80561220e+00, -1.93964236e-01,
        -4.22927546e-01,  1.06602194e+00, -8.62047607e-01,
        -2.90763707e-01],
       [-1.07316556e+00, -2.50999050e-01, -5.45049325e-01,
         9.30376622e-01,  1.35710432e+00, -1.39971876e+00,
        -1.39918093e+00, -1.78556161e+00,  3.89109048e-01,
         2.

array([ 5.54998990e-01, -6.82801331e-01,  4.27462113e-01,  1.56883148e+00,
       -3.84519873e-02, -2.91942157e-01, -1.84802245e+00, -4.63534869e-01,
       -6.46146170e-01, -1.06448844e+00,  1.07209767e+00, -8.04710991e-01,
        6.11925974e-01, -5.14159239e-01,  4.85407301e-01,  7.41236000e-01,
        6.69513159e-01,  1.02792098e+00,  1.57914363e+00, -9.59296535e-02,
       -4.41025254e-01,  1.45252316e+00,  9.98628448e-01, -4.23597907e-01,
        4.44918004e-01,  1.32930609e+00,  1.25161169e-02,  4.88572476e-01,
       -2.14411726e+00,  5.79508226e-01,  9.76426066e-02,  2.36971827e-01,
        1.48897919e-01,  2.09450969e-01, -1.80561220e+00, -1.93964236e-01,
       -4.22927546e-01,  1.06602194e+00, -8.62047607e-01, -2.90763707e-01,
       -1.07316556e+00, -2.50999050e-01, -5.45049325e-01,  9.30376622e-01,
        1.35710432e+00, -1.39971876e+00, -1.39918093e+00, -1.78556161e+00,
        3.89109048e-01,  2.55733739e-01,  4.12384957e-01, -8.45741919e-01,
       -1.19577395e+00,  

In [21]:
t = tf.ragged.constant([[3,4],[1],[2,4,7]])

NameError: name 'tf' is not defined

In [10]:
tf.gather(t, [0,1,1,0,2,0])

<tf.RaggedTensor [[3, 4], [1], [1], [3, 4], [2, 4, 7], [3, 4]]>

In [18]:
arr = np.random.randint(5, size = (10))
print(arr)
arr[[0,5,0,7]]

[4 3 4 2 4 4 2 3 3 0]


array([4, 4, 4, 3])

In [2]:
import data_vectorizer_tf

D:\KaggleLearningEquality2023\data_vectorizer_tf.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contents_vect["title_vectorize"] = contents_vect["title_vectorize"].apply(transform_string_to_list)
D:\KaggleLearningEquality2023\data_vectorizer_tf.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contents_vect["description_vectorize"] = contents_vect["description_vectorize"].apply(transform_string_to_list)
D:\KaggleLearningEquality2023\data_vectorizer_tf.py:24: SettingWithCopyWarning: 
A value is tryi

In [22]:
contents_list, topics_list, correlations = data_vectorizer_tf.random_train_batch_sample(initial_sample_size = 1000, zero_to_one_ratio = 3)

In [23]:
import time

ctime = time.time()

contents_strings = data_vectorizer.obtain_contents_vector(list(data_vectorizer.train_contents[list(contents_list)]))
topics_strings = data_vectorizer.obtain_topics_vector(list(data_vectorizer.train_topics[list(topics_list)]))

ctime = time.time() - ctime
print(ctime)

0.013391971588134766


In [24]:
ctime = time.time()

contents_strings2 = data_vectorizer_tf.obtain_train_contents_vector(contents_list)
topics_strings2 = data_vectorizer_tf.obtain_train_topics_vector(topics_list)

ctime = time.time() - ctime
print(ctime)

0.004986763000488281


In [25]:
display(contents_strings)

title_translate  \
id                                                    
c_f6c01da06f52     [390, 518, 614, 666, 1437, 2505]   
c_9571afea8a25                          [295, 1846]   
c_5c644f8c1cb4              [20, 84, 336, 625, 889]   
c_d83f7ee4e8c7                            [22, 153]   
c_a038aace794e                      [79, 220, 1706]   
...                                             ...   
c_b0aac88930e5                    [30, 34, 73, 107]   
c_ec1d7616c9f3                           [412, 434]   
c_b2288cac2bce  [20, 27, 128, 433, 467, 1178, 1405]   
c_b3c7827766e3                            [66, 325]   
c_a6a1b7b10ca7          [8, 10, 164, 487, 695, 721]   

                                            description_translate  
id                                                                 
c_f6c01da06f52                                                 []  
c_9571afea8a25                                                 []  
c_5c644f8c1cb4                    [0, 8, 26, 336, 469, 625, 1323]  
c_d83f7ee4e8c7                                                 []  
c_a038aace794e                                                 []  
...                                                           ...  
c_b0aac88930e5                                   [3, 30, 73, 107]  
c_ec1d7616c9f3                                                 []  
c_b2288cac2bce  [0, 3, 7, 16, 17, 53, 66, 90, 111, 120, 126, 1...  
c_b3c7827766e3                                                 []  
c_a6a1b7b10ca7                                                 []  

[176 rows x 2 columns]

In [26]:
contents_strings2

(<tf.RaggedTensor [[390, 518, 614, 666, 1437, 2505], [295, 1846], [20, 84, 336, 625, 889],
  [22, 153], [79, 220, 1706], [3, 19, 46, 128, 1151],
  [1, 10, 54, 104, 191, 440, 712], [1284], [105, 248, 512, 580, 735],
  [5, 25, 361, 647, 1941], [115, 602, 685, 937], [8, 60, 84, 93, 602],
  [23, 219, 289, 910, 1473], [1, 4, 101, 118, 219, 546, 1007, 1886, 2461],
  [48, 439, 513, 1117], [8, 276, 1093], [44], [13, 38, 226, 1841],
  [186, 198, 799, 1586], [25, 44], [27, 341, 2655], [13, 198, 822, 1589],
  [1608, 2348], [54, 321, 339, 402, 619, 1112, 2361], [2679],
  [135, 528, 1618, 2475], [1], [13, 345, 732, 822, 951], [86, 151, 428],
  [2, 801], [7, 27, 649, 873], [51, 63, 223, 2207], [30], [30],
  [20, 720, 2018], [3, 76, 877], [], [107], [39, 558, 981],
  [13, 35, 39, 219, 226, 263, 469], [13, 870], [273, 469, 640, 955, 2089],
  [215, 466, 1021], [1], [81, 1079, 1267], [342], [137, 1043],
  [72, 389, 986], [5, 20, 165, 889, 2511], [51, 63, 223, 2207],
  [86, 288, 306, 2508], [78, 449, 544