In [1]:
import data
import data_vectorizer
import pandas as pd
import numpy as np

In [108]:
import itertools
prod = list(itertools.product([1,2,3],[4,5,6]))
print(prod)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]


In [109]:
list(zip(*prod))

[(1, 1, 1, 2, 2, 2, 3, 3, 3), (4, 5, 6, 4, 5, 6, 4, 5, 6)]

In [9]:
z = list(zip(*[(1, 2), (3, 4), (5, 6)]))

In [8]:
display(data_vectorizer.train_contents)
display(data_vectorizer.train_topics)
display(data_vectorizer.test_contents)
display(data_vectorizer.test_topics)

Index(['c_e1d73acfff8e', 'c_433f60c8c551', 'c_bd6cb0b2064a', 'c_af05b751efdf',
       'c_d95c204965eb', 'c_82fff6f5f011', 'c_e7422d30f9de', 'c_5aee85b81df4',
       'c_ee5fdde42578', 'c_6287bfd9a353',
       ...
       'c_bc0c2f38405e', 'c_d1f6e1a4fdeb', 'c_d6152aa64456', 'c_d9f883585fae',
       'c_f281dc119ead', 'c_06e435c5adc4', 'c_1d988f48dbd1', 'c_9535009492ec',
       'c_d4456fa82c93', 'c_a3764558c917'],
      dtype='object', name='id', length=80172)

Index(['t_000095e03056', 't_00069b63a70a', 't_0008a1bd84ba', 't_000c0c854f0b',
       't_000d1fb3f2f5', 't_00102869fbcb', 't_001139e52dbe', 't_0012a45fa09c',
       't_0015856edda8', 't_00165488ad43',
       ...
       't_ffee896af9ab', 't_fff1f01cfeb0', 't_fff51448598c', 't_fff5da49c4d3',
       't_fff7782561f4', 't_fff80f4eee89', 't_fff830472691', 't_fffb0bf2801d',
       't_fffe14f1be1e', 't_fffe88835149'],
      dtype='object', name='id', length=46149)

Index(['c_639ea2ef9c95', 'c_89ce9367be10', 'c_ac1672cdcd2c', 'c_ebb7fdf10a7e',
       'c_2bbc650030f4', 'c_304ee4f59410', 'c_0baf72ed7e1e', 'c_5eca28e2cdb4',
       'c_6a5472fb1483', 'c_ccd6b2522613',
       ...
       'c_c8afdc5d35e0', 'c_0a14c601790d', 'c_4296e1773043', 'c_467c25f8af6e',
       'c_50a388dd2295', 'c_5f678fecd934', 'c_686fc8da9d9e', 'c_bfaf73de8100',
       'c_dbc8b01bad08', 'c_ec8c8f6480d0'],
      dtype='object', name='id', length=41272)

Index(['t_00068291e9a4', 't_0010852b7049', 't_001477394250', 't_0014be0167f3',
       't_0014d6945f7e', 't_001bc7125ae7', 't_001bd01717d7', 't_002336d97c88',
       't_00253e2bc084', 't_002dfcaaf1d7',
       ...
       't_ffd908252a7d', 't_ffdc013937fc', 't_ffdfd53288a4', 't_ffe5264dc46d',
       't_ffe546d714a1', 't_ffe719589252', 't_fff05585df72', 't_fff5d93d4dc2',
       't_fff7f2dd208b', 't_fffe811a6da9'],
      dtype='object', name='id', length=14469)

In [104]:
initial_sample_size = 1000
contents_list = data_vectorizer.random_train_contents_sample(initial_sample_size)
topics_list = data_vectorizer.random_train_topics_sample(initial_sample_size)
cor_frame = data_vectorizer.obtain_correlation_frame(topics_list, contents_list)

print(cor_frame.sum().sum())

45.0


In [105]:
cor_mat = cor_frame.to_numpy().astype(dtype = np.int32)

zero_to_one_ratio = 100
one_locations = np.where(cor_mat == 1)
zero_locations = np.where(cor_mat == 0)
stopics = list(one_locations[0])
scontents = list(one_locations[1])

one_length = len(stopics)
zero_length = int(one_length * zero_to_one_ratio)
correlations = [1] * one_length
correlations.extend([0] * zero_length)

zero_samples = list(np.random.choice(len(zero_locations[0]), zero_length, replace=False))
stopics.extend(zero_locations[0][zero_samples])
scontents.extend(zero_locations[1][zero_samples])

stopics = topics_list[stopics]
scontents = contents_list[scontents]

for k in range(len(correlations)):
    if int(cor_frame.loc[stopics[k], scontents[k]]) != correlations[k]:
        print("Error:   ", stopics[k]," ", scontents[k])
        
print(cor_mat.sum())
print(len(correlations))

45
4545


In [58]:
rint = np.random.randint(2, size = 10)
display(rint)
display(rint[[3,1,5]])

array([0, 1, 1, 0, 1, 0, 1, 1, 0, 1])

array([0, 1, 0])

In [47]:
print(correlations)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [24]:
mat = np.random.normal(size = (11, 10))
display(mat)
display(mat.flatten())

array([[ 5.54998990e-01, -6.82801331e-01,  4.27462113e-01,
         1.56883148e+00, -3.84519873e-02, -2.91942157e-01,
        -1.84802245e+00, -4.63534869e-01, -6.46146170e-01,
        -1.06448844e+00],
       [ 1.07209767e+00, -8.04710991e-01,  6.11925974e-01,
        -5.14159239e-01,  4.85407301e-01,  7.41236000e-01,
         6.69513159e-01,  1.02792098e+00,  1.57914363e+00,
        -9.59296535e-02],
       [-4.41025254e-01,  1.45252316e+00,  9.98628448e-01,
        -4.23597907e-01,  4.44918004e-01,  1.32930609e+00,
         1.25161169e-02,  4.88572476e-01, -2.14411726e+00,
         5.79508226e-01],
       [ 9.76426066e-02,  2.36971827e-01,  1.48897919e-01,
         2.09450969e-01, -1.80561220e+00, -1.93964236e-01,
        -4.22927546e-01,  1.06602194e+00, -8.62047607e-01,
        -2.90763707e-01],
       [-1.07316556e+00, -2.50999050e-01, -5.45049325e-01,
         9.30376622e-01,  1.35710432e+00, -1.39971876e+00,
        -1.39918093e+00, -1.78556161e+00,  3.89109048e-01,
         2.

array([ 5.54998990e-01, -6.82801331e-01,  4.27462113e-01,  1.56883148e+00,
       -3.84519873e-02, -2.91942157e-01, -1.84802245e+00, -4.63534869e-01,
       -6.46146170e-01, -1.06448844e+00,  1.07209767e+00, -8.04710991e-01,
        6.11925974e-01, -5.14159239e-01,  4.85407301e-01,  7.41236000e-01,
        6.69513159e-01,  1.02792098e+00,  1.57914363e+00, -9.59296535e-02,
       -4.41025254e-01,  1.45252316e+00,  9.98628448e-01, -4.23597907e-01,
        4.44918004e-01,  1.32930609e+00,  1.25161169e-02,  4.88572476e-01,
       -2.14411726e+00,  5.79508226e-01,  9.76426066e-02,  2.36971827e-01,
        1.48897919e-01,  2.09450969e-01, -1.80561220e+00, -1.93964236e-01,
       -4.22927546e-01,  1.06602194e+00, -8.62047607e-01, -2.90763707e-01,
       -1.07316556e+00, -2.50999050e-01, -5.45049325e-01,  9.30376622e-01,
        1.35710432e+00, -1.39971876e+00, -1.39918093e+00, -1.78556161e+00,
        3.89109048e-01,  2.55733739e-01,  4.12384957e-01, -8.45741919e-01,
       -1.19577395e+00,  

In [4]:
import time.

contents_list, topics_list, correlations = data_vectorizer.random_train_batch_sample(initial_sample_size = 1000, zero_to_one_ratio = 1000)

contents_strings = data_vectorizer.obtain_contents_vector(contents_list)
topics_strings = data_vectorizer.obtain_topics_vector(topics_list)

In [21]:
display(contents_strings)
display(list(contents_strings["title_translate"]))
display(list(contents_strings["description_translate"]))
display(topics_strings)

title_translate  \
id                                             
c_1fcd5914f630                        [1002]   
c_66e75986e241            [76, 95, 107, 264]   
c_c5af247d029f               [27, 439, 2117]   
c_40b1fea5ad01         [21, 140, 1521, 1923]   
c_4f741267ff3e       [26, 30, 121, 469, 769]   
...                                      ...   
c_78213853808c                     [3, 1044]   
c_86b1b2a1b2a6  [181, 751, 1278, 2006, 2390]   
c_4039eba05576                          [22]   
c_4fbc78f3c594                [31, 514, 558]   
c_1cb11e0db029               [17, 198, 2429]   

                                            description_translate  
id                                                                 
c_1fcd5914f630                                 [1002, 1720, 2222]  
c_66e75986e241                                                 []  
c_c5af247d029f  [0, 4, 20, 60, 149, 183, 230, 357, 365, 395, 4...  
c_40b1fea5ad01                [31, 69, 140, 240, 305, 1521, 1923]  
c_4f741267ff3e            [18, 26, 30, 116, 121, 302, 1162, 2154]  
...                                                           ...  
c_78213853808c                                       [3, 80, 204]  
c_86b1b2a1b2a6                                 [1278, 1827, 2006]  
c_4039eba05576                                          [83, 602]  
c_4fbc78f3c594                                                 []  
c_1cb11e0db029                    [2, 4, 17, 184, 198, 989, 2429]  

[80 rows x 2 columns]

[[1002],
 [76, 95, 107, 264],
 [27, 439, 2117],
 [21, 140, 1521, 1923],
 [26, 30, 121, 469, 769],
 [223, 1223, 1886],
 [754],
 [23, 148, 289],
 [35, 219, 226, 558, 602, 2427],
 [91, 133, 263, 933],
 [167, 289, 2649, 2668],
 [722, 1445, 1802],
 [775, 1011],
 [385, 469, 664, 1058, 2385],
 [48, 508, 2092],
 [1, 6, 10, 11, 43, 54, 183],
 [128, 949, 1033],
 [9, 40, 196, 503],
 [5, 178, 739, 1025],
 [5, 22, 178, 739],
 [7, 19, 46, 47, 137, 189, 314, 408],
 [14, 1211],
 [50, 151],
 [7, 9, 35, 101, 178],
 [0, 12, 840],
 [1],
 [608, 1721, 1856],
 [7, 19, 20, 236],
 [13, 178, 185, 778],
 [7, 35, 261, 285],
 [86, 151, 267, 325, 2391],
 [10, 50, 59, 380, 567, 1310],
 [1, 10, 50, 192, 380, 567],
 [8, 214, 223, 1633],
 [128, 1730],
 [16, 17, 407],
 [5, 178, 739, 2511],
 [108, 1831],
 [4, 814, 816],
 [4, 272, 279, 2486],
 [450],
 [30, 677],
 [1, 6, 10, 50, 280, 621, 1407],
 [291, 1833, 2726],
 [],
 [5, 25, 239],
 [82, 1495, 1755],
 [15, 671],
 [72],
 [347, 367, 388],
 [1, 10, 50, 54, 280, 970, 1332],

[[1002, 1720, 2222],
 [],
 [0,
  4,
  20,
  60,
  149,
  183,
  230,
  357,
  365,
  395,
  402,
  439,
  458,
  461,
  471,
  560,
  905,
  947,
  1085,
  2117],
 [31, 69, 140, 240, 305, 1521, 1923],
 [18, 26, 30, 116, 121, 302, 1162, 2154],
 [96, 223, 1223, 1886],
 [],
 [95, 148, 1670, 2333],
 [],
 [18, 53, 91, 263, 933, 2427],
 [7, 289, 499, 1491, 2649, 2668],
 [],
 [],
 [7, 13, 18, 119, 143, 200, 309, 385, 664, 672, 1058, 1707, 2385],
 [0,
  4,
  12,
  85,
  97,
  152,
  190,
  204,
  260,
  396,
  522,
  587,
  710,
  780,
  1013,
  1333,
  2085,
  2092,
  2158],
 [7, 24, 54, 147, 259, 1849],
 [0, 3, 128, 949, 1033],
 [8, 37, 40, 84, 196, 240, 393, 442, 503],
 [0, 5, 13, 70, 178, 739],
 [0, 2, 5, 178, 739, 1184],
 [],
 [],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  11,
  16,
  17,
  21,
  24,
  50,
  55,
  56,
  73,
  74,
  90,
  92,
  106,
  126,
  170,
  176,
  186,
  187,
  207,
  210,
  214,
  225,
  246,
  248,
  251,
  274,
  305,
  375,
  378,
  429,
  430,
  451,
  466,
  479,
 

title_translate  \
id                                      
t_4e3000770d6e                  [365]   
t_771f4b60993c  [23, 30, 67, 73, 891]   
t_9d47dd05d31a  [140, 183, 905, 1521]   
t_9d47dd05d31a  [140, 183, 905, 1521]   
t_d78298b619f1       [7, 21, 30, 302]   
...                               ...   
t_8ab905868551  [36, 108, 1272, 1689]   
t_046ab474b8c9             [311, 696]   
t_46fdc0d03d94                    [1]   
t_729884e82472              [20, 734]   
t_7566b8b2beb9       [283, 975, 1087]   

                                            description_translate  
id                                                                 
t_4e3000770d6e  [0, 2, 3, 56, 65, 146, 166, 348, 365, 482, 595...  
t_771f4b60993c  [0, 1, 2, 27, 30, 65, 67, 73, 106, 107, 108, 1...  
t_9d47dd05d31a  [0, 2, 3, 57, 74, 89, 140, 183, 190, 240, 245,...  
t_9d47dd05d31a  [0, 2, 3, 57, 74, 89, 140, 183, 190, 240, 245,...  
t_d78298b619f1                                                 []  
...                                                           ...  
t_8ab905868551                                    [342, 367, 786]  
t_046ab474b8c9  [0, 2, 258, 266, 696, 707, 924, 1082, 1140, 2374]  
t_46fdc0d03d94                                                 []  
t_729884e82472                                                 []  
t_7566b8b2beb9                                                 []  

[80 rows x 2 columns]

In [42]:
k = 5
lst = []
for j in range(k):
    lst.append(list(np.random.choice(5, np.random.randint(5), replace=False)))
print(lst)

[[0, 2, 4, 3], [3, 2, 1], [2], [4, 1], [3]]


In [43]:
np.random.randint(2, size = k)

array([0, 1, 0, 1, 0])

In [4]:
display(data.contents)

title  \
id                                                                 
c_00002381196d  Sumar números de varios dígitos: 48,029+233,930    
c_000087304a9e                    Trovare i fattori di un numero   
c_0000ad142ddb                           Sumar curvas de demanda   
c_0000c03adc8d                               Nado de aproximação   
c_00016694ea2a                  geometry-m3-topic-a-overview.pdf   
...                                                          ...   
c_fffcbdd4de8b                                  2. 12: Diffusion   
c_fffe15a2d069                      Sommare facendo gruppi da 10   
c_fffed7b0d13a                            Introdução à subtração   
c_ffff04ba7ac7                                      SA of a Cone   
c_ffffe5254266                                          The Jats   

                                                      description      kind  \
id                                                                            
c_00002381196d  Suma 48,029+233,930 mediante el algoritmo está...     video   
c_000087304a9e                    Sal trova i fattori di 120.\n\n     video   
c_0000ad142ddb                  Cómo añadir curvas de demanda\n\n     video   
c_0000c03adc8d  Neste vídeo você vai aprender o nado de aproxi...  document   
c_00016694ea2a                   geometry-m3-topic-a-overview.pdf  document   
...                                                           ...       ...   
c_fffcbdd4de8b                                                NaN     html5   
c_fffe15a2d069  Sal somma 5+68 spezzando il 5 in un 2 e un 3.\n\n     video   
c_fffed7b0d13a  Sal fala sobre o que significa subtrair. Os ex...     video   
c_ffff04ba7ac7                                                NaN     video   
c_ffffe5254266                                                NaN     video   

                                                             text language  \
id                                                                           
c_00002381196d                                                NaN       es   
c_000087304a9e                                                NaN       it   
c_0000ad142ddb                                                NaN       es   
c_0000c03adc8d  \nNado de aproximação\nSaber nadar nas ondas ...       pt   
c_00016694ea2a  Estándares Comunes del Estado de Nueva York\n\...       es   
...                                                           ...      ...   
c_fffcbdd4de8b  What will eventually happen to these dyes?\n\n...       en   
c_fffe15a2d069                                                NaN       it   
c_fffed7b0d13a                                                NaN       pt   
c_ffff04ba7ac7                                                NaN       en   
c_ffffe5254266                                                NaN       en   

                copyright_holder      license  \
id                                              
c_00002381196d               NaN          NaN   
c_000087304a9e               NaN          NaN   
c_0000ad142ddb               NaN          NaN   
c_0000c03adc8d  Sikana Education  CC BY-NC-ND   
c_00016694ea2a         Engage NY  CC BY-NC-SA   
...                          ...          ...   
c_fffcbdd4de8b    CSU and Merlot  CC BY-NC-SA   
c_fffe15a2d069               NaN          NaN   
c_fffed7b0d13a               NaN          NaN   
c_ffff04ba7ac7               NaN          NaN   
c_ffffe5254266               NaN          NaN   

                                        title_translate  \
id                                                        
c_00002381196d  Add multi-digit numbers: 48,029+233,930   
c_000087304a9e              Finding factors of a number   
c_0000ad142ddb                        Add demand curves   
c_0000c03adc8d                            Approach node   
c_00016694ea2a         geometry-m3-topic-a-overview.pdf   
...                                                 ...   
c_fffcbdd4de8b       